/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td2;

import java.util.function.Predicate;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public void question2 (){
        Predicate<Integer> tropPetite = taille -> taille <100;
        Predicate<Integer> tropGrande = taille -> taille >200;
        Predicate<Integer> tailleIncorrecte = tropPetite.or(tropGrande);
        Predicate<Integer> tailleCorrecte = tailleIncorrecte.negate();

        Predicate<Double> tropLourd = poids -> poids > 150.0;
        Predicate<Double> poidsCorrect = tropLourd.negate();
       

    }
}
